### ISSUE TITLE
default install

### ISSUE THREAD

**Issue by kinomakino** [mushorg/imhoneypot#2]
Thanks for all
default install modules the script send this error:

Tue, 22 Mar 2016 11:29:57 - IMHoneypot Console Logger - DEBUG - Starting IMHoneypot...
Traceback (most recent call last):
  File "imhoneypot.py", line 144, in <module>
    honeypot = IMHoneypot()
  File "imhoneypot.py", line 42, in __init__
    self.sqlite_db = modules.sqlite.SQLiteDB()
TypeError: __init__() takes exactly 2 arguments (1 given)

thanks for all !!!

**Comment by glaslos** [comment]
Pull the latest source and try again. i haven't used this tool in ages, not sure if it still works.

**Comment by kinomakino** [comment]
thanks so mucho: now i have other problem:

 Traceback (most recent call last):
  File "imhoneypot.py", line 144, in <module>
    honeypot = IMHoneypot()
  File "imhoneypot.py", line 43, in **init**
    self.sqlite_db.create()
  File "/home/azureuser/imhoneypot/modules/sqlite.py", line 12, in create
    db = sqlite3.connect('db/sqlite.db')
sqlite3.OperationalError: unable to open database file

**Comment by glaslos** [comment]
In the honeypot folder:
mkdir db
touch db/sqlite.db
Then try again.

**Comment by kinomakino** [comment]
thanks you so much !!!

If you don´t want to cotinue, tell me xD

now the problem is with Purple Module xD

Traceback (most recent call last):
  File "imhoneypot.py", line 144, in <module>
    honeypot = IMHoneypot()
  File "imhoneypot.py", line 53, in **init**
    self.core = purple.Purple(name, version, website, dev_website, debug_enabled=True, default_path="prefs")
AttributeError: 'module' object has no attribute 'Purple'

**Comment by glaslos** [comment]
Are you running the sh script?
